name: Deploy Frontend to Hugging Face Spaces

on:
  push:
    branches: [ main ]
    paths: [ 'app/**', 'package.json', 'next.config.js', 'tailwind.config.js', 'tsconfig.json' ]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build frontend
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: https://helloraviai-vidyaai-backend.hf.space
        
    - name: Deploy to Hugging Face Spaces
      uses: huggingface/huggingface_hub@v0.19.4
      with:
        hf_token: ${{ secrets.HF_TOKEN }}
        local_dir: ./out
        repo_id: helloraviai/vidyaai-frontend
        repo_type: space
        space_sdk: static
        commit_message: "Auto-deploy from GitHub Actions - ${{ github.sha }}"
